apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: producao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: homamalsuyoufi/chaminatechbackend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service.producao.svc.cluster.local:5432/chaminatech
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: APP_ALLOWED_ORIGIN
              value: "https://chaminatech.com"
          resources:
            requests:
              cpu: "1000m"       # 1 vCPU garantido
              memory: "2Gi"      # 2 GB garantidos
            limits:
              cpu: "2"           # limite máximo 2 vCPUs
              memory: "4Gi"  
